spring:
  datasource:
    name: research_data
    url: jdbc:mysql://localhost:3306/research_data
    username: root
    password: wangshuai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: info
server:
  servlet:
    session:
      timeout: 3600

