spring:
  datasource:
    name: research_data
    url: jdbc:mysql://localhost:3306/research_data
    username: root
    password: wangshuai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: info
server:
  servlet:
    session:
      timeout: 3600
  tomcat:
    max-swallow-size: 400MB

