package com.sau.data.entity;

import java.util.Date;

public class CodeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.id
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_description
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String codeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_label
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String codeLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String codeFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.code_readme
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String codeReadme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code.create_time
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.id
     *
     * @return the value of code.id
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.id
     *
     * @param id the value for code.id
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_name
     *
     * @return the value of code.code_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_name
     *
     * @param codeName the value for code.code_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_description
     *
     * @return the value of code.code_description
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getCodeDescription() {
        return codeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_description
     *
     * @param codeDescription the value for code.code_description
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCodeDescription(String codeDescription) {
        this.codeDescription = codeDescription == null ? null : codeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_label
     *
     * @return the value of code.code_label
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getCodeLabel() {
        return codeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_label
     *
     * @param codeLabel the value for code.code_label
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCodeLabel(String codeLabel) {
        this.codeLabel = codeLabel == null ? null : codeLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_file
     *
     * @return the value of code.code_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getCodeFile() {
        return codeFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_file
     *
     * @param codeFile the value for code.code_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCodeFile(String codeFile) {
        this.codeFile = codeFile == null ? null : codeFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.code_readme
     *
     * @return the value of code.code_readme
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getCodeReadme() {
        return codeReadme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.code_readme
     *
     * @param codeReadme the value for code.code_readme
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCodeReadme(String codeReadme) {
        this.codeReadme = codeReadme == null ? null : codeReadme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code.create_time
     *
     * @return the value of code.create_time
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code.create_time
     *
     * @param createTime the value for code.create_time
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}