package com.sau.data.entity;

import java.util.Date;

public class CodeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.id
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.code_name
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.code_description
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private String codeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.code_label
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private String codeLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.code_file
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private String codeFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.code_readme
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private String codeReadme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.create_time
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_info.user_name
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.id
     *
     * @return the value of code_info.id
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.id
     *
     * @param id the value for code_info.id
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.code_name
     *
     * @return the value of code_info.code_name
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.code_name
     *
     * @param codeName the value for code_info.code_name
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.code_description
     *
     * @return the value of code_info.code_description
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public String getCodeDescription() {
        return codeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.code_description
     *
     * @param codeDescription the value for code_info.code_description
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setCodeDescription(String codeDescription) {
        this.codeDescription = codeDescription == null ? null : codeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.code_label
     *
     * @return the value of code_info.code_label
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public String getCodeLabel() {
        return codeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.code_label
     *
     * @param codeLabel the value for code_info.code_label
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setCodeLabel(String codeLabel) {
        this.codeLabel = codeLabel == null ? null : codeLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.code_file
     *
     * @return the value of code_info.code_file
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public String getCodeFile() {
        return codeFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.code_file
     *
     * @param codeFile the value for code_info.code_file
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setCodeFile(String codeFile) {
        this.codeFile = codeFile == null ? null : codeFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.code_readme
     *
     * @return the value of code_info.code_readme
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public String getCodeReadme() {
        return codeReadme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.code_readme
     *
     * @param codeReadme the value for code_info.code_readme
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setCodeReadme(String codeReadme) {
        this.codeReadme = codeReadme == null ? null : codeReadme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.create_time
     *
     * @return the value of code_info.create_time
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.create_time
     *
     * @param createTime the value for code_info.create_time
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_info.user_name
     *
     * @return the value of code_info.user_name
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_info.user_name
     *
     * @param userName the value for code_info.user_name
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}