package com.sau.data.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class OtherFileDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_file.id
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_file.file_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_file.file_description
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String fileDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_file.file_address
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String fileAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_file.user_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_file.create_time
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_file.id
     *
     * @return the value of other_file.id
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_file.id
     *
     * @param id the value for other_file.id
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_file.file_name
     *
     * @return the value of other_file.file_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_file.file_name
     *
     * @param fileName the value for other_file.file_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_file.file_description
     *
     * @return the value of other_file.file_description
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_file.file_description
     *
     * @param fileDescription the value for other_file.file_description
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setFileDescription(String fileDescription) {
        this.fileDescription = fileDescription == null ? null : fileDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_file.file_address
     *
     * @return the value of other_file.file_address
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getFileAddress() {
        return fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_file.file_address
     *
     * @param fileAddress the value for other_file.file_address
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress == null ? null : fileAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_file.user_name
     *
     * @return the value of other_file.user_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_file.user_name
     *
     * @param userName the value for other_file.user_name
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_file.create_time
     *
     * @return the value of other_file.create_time
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_file.create_time
     *
     * @param createTime the value for other_file.create_time
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}