package com.sau.data.entity;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_id
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_name
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.password
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_id
     *
     * @return the value of student_info.student_id
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_id
     *
     * @param studentId the value for student_info.student_id
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_name
     *
     * @return the value of student_info.student_name
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_name
     *
     * @param studentName the value for student_info.student_name
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.password
     *
     * @return the value of student_info.password
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.password
     *
     * @param password the value for student_info.password
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}