package com.sau.data.entity;

public class TagDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.id
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.tag_name
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    private String tagName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.id
     *
     * @return the value of tag_info.id
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.id
     *
     * @param id the value for tag_info.id
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.tag_name
     *
     * @return the value of tag_info.tag_name
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.tag_name
     *
     * @param tagName the value for tag_info.tag_name
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }
}