package com.sau.data.entity;

public class TeacherDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_id
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_name
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.password
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_id
     *
     * @return the value of teacher_info.teacher_id
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_id
     *
     * @param teacherId the value for teacher_info.teacher_id
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_name
     *
     * @return the value of teacher_info.teacher_name
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_name
     *
     * @param teacherName the value for teacher_info.teacher_name
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.password
     *
     * @return the value of teacher_info.password
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.password
     *
     * @param password the value for teacher_info.password
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}