package com.sau.data.dao;

import com.sau.data.entity.CodeDO;
import com.sau.data.form.CodeForm;
import com.sun.tools.javac.jvm.Code;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_info
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_info
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    int insert(CodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_info
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    int insertSelective(CodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_info
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    CodeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_info
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    int updateByPrimaryKeySelective(CodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_info
     *
     * @mbg.generated Sat Dec 26 16:16:59 CST 2020
     */
    int updateByPrimaryKey(CodeDO record);

    /**
     * @Description: 获取总数
     * @return:
     */
    int getTotal(CodeForm codeForm);

    /**
     * @Description: 获取List
     * @return:
     */
    List<CodeDO> selectFileListPage(CodeForm codeForm);
}