package com.sau.data.dao;

import com.sau.data.entity.OtherFileDO;
import com.sau.data.form.OtherFileForm;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OtherFileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insert(OtherFileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insertSelective(OtherFileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    OtherFileDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKeySelective(OtherFileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKey(OtherFileDO record);

    /**
     * @Description: 按条件查询总数
     * @return:
     */
     Integer getTotal(OtherFileForm form);

     /**
      * @Description: 按条件分页
      * @return: java.util.List<com.sau.data.entity.OtherFileDO>
      */
    List<OtherFileDO> selectFileListPage(OtherFileForm otherFileForm);
}