package com.sau.data.dao;

import com.sau.data.entity.PaperDO;
import org.springframework.stereotype.Repository;

@Repository
public interface PaperDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insert(PaperDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insertSelective(PaperDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    PaperDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKeySelective(PaperDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_info
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKey(PaperDO record);
}