package com.sau.data.dao;

import com.sau.data.entity.StudyDO;
import org.springframework.stereotype.Repository;

@Repository
public interface StudyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insert(StudyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insertSelective(StudyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    StudyDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKeySelective(StudyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKey(StudyDO record);
}