package com.sau.data.dao;

import com.sau.data.entity.StudyDO;
import com.sau.data.form.StudyFileForm;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StudyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insert(StudyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int insertSelective(StudyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    StudyDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKeySelective(StudyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_file
     *
     * @mbg.generated Fri Dec 18 21:56:50 CST 2020
     */
    int updateByPrimaryKey(StudyDO record);

    /**
     * @Description: 获取所有数量
     * @return: int
     */
    int getTotal(StudyFileForm studyFileForm);

    /**
     * @Description: 获取所有文件
     * @return:
     */
    List<StudyDO>  selectFileListPage(StudyFileForm studyFileForm);
}