package com.sau.data.dao;

import com.sau.data.entity.TagDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TagDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    int insert(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    int insertSelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    TagDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    int updateByPrimaryKeySelective(TagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Sat Dec 26 16:25:03 CST 2020
     */
    int updateByPrimaryKey(TagDO record);

    /**
     * @Description: 查询所有标签
     * @return: java.util.List<com.sau.data.entity.TagDO>
     */
    List<TagDO> selectAllTags();

    /**
     * @Description: 按名称查询
     * @return:
     */
    TagDO selectByName(String tagName);
}