package com.sau.data.dao;

import com.sau.data.entity.TeacherDO;

public interface TeacherDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    int insert(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    int insertSelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    TeacherDO selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    int updateByPrimaryKeySelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_info
     *
     * @mbg.generated Mon Dec 07 23:07:35 CST 2020
     */
    int updateByPrimaryKey(TeacherDO record);
}